name: Visual experiments with processing
url: http://odhondt.github.io/p5lab/
description: Experiments in creative coding with processing.org
permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true
